<a href="https://colab.research.google.com/github/Maurya-Grover/ML_DS_Prac/blob/main/Numpy/NumpyPrac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

In [24]:
a = np.array([4, 65, 8, 9, 2, 1, 0, 2, 10, 12391672381, -45, -45, -45, 12])

In [25]:
np.zeros([3,4], dtype = np.int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
np.zeros([3,4], dtype = np.float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones([3,4], dtype = np.float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones([3,4], dtype = np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros(5, dtype = np.int) # same for np.ones

array([0, 0, 0, 0, 0])

In [30]:
np.zeros_like(a, dtype = np.int) # same size as np array can be done same for ones_like

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.full((5,3), 45, dtype = np.int)

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [31]:
np.linspace(1, 143, 12)

array([  1.        ,  13.90909091,  26.81818182,  39.72727273,
        52.63636364,  65.54545455,  78.45454545,  91.36363636,
       104.27272727, 117.18181818, 130.09090909, 143.        ])