<a href="https://colab.research.google.com/github/Maurya-Grover/ML_DS_Prac/blob/main/Numpy/NumpyPrac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

In [2]:
a = np.array([4, 65, 8, 9, 2, 1, 0, 2, 10, 12391672381, -45, -45, -45, 12])

In [3]:
np.zeros([3,4], dtype = np.int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.zeros([3,4], dtype = np.float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones([3,4], dtype = np.float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.ones([3,4], dtype = np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
np.zeros(5, dtype = np.int) # same for np.ones

array([0, 0, 0, 0, 0])

In [8]:
np.zeros_like(a, dtype = np.int) # same size as np array can be done same for ones_like

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.full((5,3), 45, dtype = np.int)

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [10]:
np.full(a.shape, 44, dtype = np.int)

array([44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44])

In [11]:
np.full_like(a, 44, dtype = np.int)

array([44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44])

In [12]:
np.linspace(1, 143, 12)

array([  1.        ,  13.90909091,  26.81818182,  39.72727273,
        52.63636364,  65.54545455,  78.45454545,  91.36363636,
       104.27272727, 117.18181818, 130.09090909, 143.        ])

# Random Numbers


In [13]:
np.random.rand(4,2)

array([[0.93195216, 0.0519823 ],
       [0.34154295, 0.6076475 ],
       [0.69796434, 0.9849939 ],
       [0.28189698, 0.8642634 ]])

In [14]:
np.random.random_sample(a.shape)

array([0.80234524, 0.9249337 , 0.24894571, 0.43081035, 0.20910759,
       0.14885783, 0.2444944 , 0.64076561, 0.92505479, 0.80045646,
       0.17357577, 0.09925532, 0.25615255, 0.17201793])

In [15]:
np.random.randint(7, size = (3,5))

array([[2, 1, 4, 5, 4],
       [6, 6, 1, 3, 0],
       [0, 6, 1, 4, 2]])

In [16]:
np.random.randint(7, 324, size = (3,4))

array([[238, 222,  27,  98],
       [155, 122, 312, 322],
       [ 61,  61,  33, 281]])

In [17]:
np.random.randint(7, 324, size = a.shape)

array([129, 171, 261, 233, 175, 110, 225, 186, 118,  45, 118, 102,  37,
        85])

In [18]:
np.identity(4, dtype = np.int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0) # axis = 0 means rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
